### ISSUE TITLE
What does apply () do here？

### ISSUE THREAD

**Issue by zanyatta** [WangZhechao/expross#1]
day1/lib/application.js:46

我把 `server.listen.apply(server, arguments);` 换成 `server.listen(arguments);`
会导致报错：
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'options' must have the property "port" or "path". Received [Arguments] { '0': 3000, '1': [Function (anonymous)] }

我的问题是：
1.为什么使用apply就不会报错？
2.apply()导致的this切换的直接作用是什么？

**Comment by WangZhechao** [comment]
呃，这个问题没有你想的那么复杂，先说一下为什么用 apply：

用 apply 的原因主要是 listen 函数重载形式很多，参数的样式不确定，如果想将这些参数传递给另一个函数，在无法获取当前参数样式的情况下，才用了 apply(server, arguments)，举个例子：

假设现在这个 add 函数有两个形式：

```
function add(a, b) { ... } //计算 a + b
function add(arr) {...} //计算整个数组 arr 的和
```
然后你自定义一个函数做一些其它功能，其中需要使用到 add：
```
function test() {
    //....
   add()
   //....
}
```
你想 test 同样支持两种形式：
```
test(1,2)
test([1,2])
```
这时候你会发现，在 test 函数中你无法直接确定调用 add 的哪种形式，你只有两种方法，一种是手动区分当前的参数样式是哪一种，另一种方式就是直接使用 apply 传入，无需考虑参数样式。这就是使用 apply 的原因。

第二个，说一下为什么报错，这个报错的原因是 listen 不支持传入 argument 参数的类型，具体可以看 listen 中处理重载的方式：https://github.com/nodejs/node/blob/d129e0c782914df8720d1335c95bd7f635f2788e/lib/net.js#L198

argument 这个是一个专有类型，类似数组，你应该有所了解。如果你直接传入 argument，传入的是 argument 本身，而使用 apply 传入，传入的是 argument 内部包含的东西。一样举个例子：

```
function add(a, b) {
    console.log(typeof a, typeof b)
    return a + b
}

function test(a, b) {
    add(a, b)
    add(arguments)
    add.apply(null, arguments)
}

test(1, 3)
```

执行后，结果：

number number
object undefined
number number

关于 this 指针，这里你用 server.listen.apply(server, arguments); 和 server.listen(arguments); 没区别，都是指向 server 对象的。

**Comment by zanyatta** [comment]
原来如此！多谢！
